// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;
using Binding;

namespace FIApp.iOS
{
	public partial class SampleViewController : UIViewController {

		string applicationName;
		string baseUrl;
		string institutionId;
		string ssoKey;
		string product;

		public SampleViewController (string applicationName, string baseUrl, string institutionId, string ssoKey, string product) 
		{
			this.applicationName = applicationName;
			this.baseUrl = baseUrl;
			this.institutionId = institutionId;
			this.ssoKey = ssoKey;
			this.product = product;
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
            var zelle = new ZelleProxy();
			zelle.LaunchZelleWithViewController(this, applicationName, baseUrl, institutionId, ssoKey, product);
            //zelle.LaunchZelleSDKWithViewController(this);
        }
	}
}
