// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FIApp.iOS
{
	public partial class Sample : UIView
	{
		public Sample (IntPtr handle) : base (handle)
		{
		}
	}
}
